---
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: vagrant 
ansible_password: vagrant
ansible_sudo_pass: vagrant 
docker_network_name: custom_net
webapp_image: nginxdemos/hello
container_name: webapp1

